/*****************************************************************************
 * Source code information
 * -----------------------
 * Original author    Andreas Langegger, Johannes Kepler University Linz, Austria
 * Author email       al@jku.at
 * Package            @package@
 * Web site           @website@
 * Created            13 Jan 2010 14:17
 * @copyright@
 *****************************************************************************/

// Package
///////////////////////////////////////
package at.jku.semwiq.mediator.vocabulary;

// Imports
///////////////////////////////////////
import com.hp.hpl.jena.rdf.model.*;


/**
 * Vocabulary definitions from file:vocabulary/purl.org/semwiq/mediator/config.n3
 * @author Auto-generated by schemagen on 13 Jan 2010 14:17
 */
public class Config {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/semwiq/mediator/config#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    



    /* Vocabulary properties */

    /** <p>URL of a SemWIQ configuration file (e.g. file:... or http://...).</p> */
    public static final Property configFile = m_model.createProperty( "http://purl.org/semwiq/mediator/config#configFile" );
    
    /** <p>Configuration of the DataSourceRegistry including RDFStats and the data source 
     *  monitor</p>
     */
    public static final Property dataSourceRegistryConfig = m_model.createProperty( "http://purl.org/semwiq/mediator/config#dataSourceRegistryConfig" );
    
    /** <p>Configuration of query federator</p> */
    public static final Property federatorConfig = m_model.createProperty( "http://purl.org/semwiq/mediator/config#federatorConfig" );
    
    /** <p>Global RDFStats configuration (ignoring some properties such as stats:endpoint, 
     *  stats:outputFile, and stats:outputFormat). Specific configurations can be 
     *  set for each data source with a sdv:CentralizedMonitoringProfile.</p>
     */
    public static final Property globalStatsConfig = m_model.createProperty( "http://purl.org/semwiq/mediator/config#globalStatsConfig" );
    
    /** <p>Configuration of the graphical user interface (used for both, the web application 
     *  and the Java swing client</p>
     */
    public static final Property guiConfig = m_model.createProperty( "http://purl.org/semwiq/mediator/config#guiConfig" );
    
    /** <p>enables type inference, default is true</p> */
    public static final Property inferTypes = m_model.createProperty( "http://purl.org/semwiq/mediator/config#inferTypes" );
    
    /** <p>The namespace</p> */
    public static final Property namespace = m_model.createProperty( "http://purl.org/semwiq/mediator/config#namespace" );
    
    /** <p>The prefix string</p> */
    public static final Property prefix = m_model.createProperty( "http://purl.org/semwiq/mediator/config#prefix" );
    
    /** <p>Adds a prefix mapping to the query widget (HTML form in the Web application 
     *  or Java SWING text widget.</p>
     */
    public static final Property prefixMapping = m_model.createProperty( "http://purl.org/semwiq/mediator/config#prefixMapping" );
    
    /** <p>A name for the query (may be used as tab title in the GUI)</p> */
    public static final Property queryName = m_model.createProperty( "http://purl.org/semwiq/mediator/config#queryName" );
    
    /** <p>The lexical SPARQL query string.</p> */
    public static final Property queryString = m_model.createProperty( "http://purl.org/semwiq/mediator/config#queryString" );
    
    /** <p>A sample query to show in the GUI after startup.</p> */
    public static final Property sampleQuery = m_model.createProperty( "http://purl.org/semwiq/mediator/config#sampleQuery" );
    
    /** <p>assembled Jena model used by DataSourceRegistry, UserRegistry, and RDFStats 
     *  statistics</p>
     */
    public static final Property store = m_model.createProperty( "http://purl.org/semwiq/mediator/config#store" );
    
    /** <p>enable subsumption reasoning if not supported natively by a data source, default 
     *  is true</p>
     */
    public static final Property subsumption = m_model.createProperty( "http://purl.org/semwiq/mediator/config#subsumption" );
    
    /** <p>Password for super user</p> */
    public static final Property superuserPassword = m_model.createProperty( "http://purl.org/semwiq/mediator/config#superuserPassword" );
    
    /** <p>Configuration of the UserRegistry</p> */
    public static final Property userRegistryConfig = m_model.createProperty( "http://purl.org/semwiq/mediator/config#userRegistryConfig" );
    

    /* Vocabulary classes */

    /** <p>Configuration of the DataSourceRegistry</p> */
    public static final Resource DataSourceRegistryConfig = m_model.createResource( "http://purl.org/semwiq/mediator/config#DataSourceRegistryConfig" );
    
    /** <p>Abstract configuration class of the Query Processor</p> */
    public static final Resource FederatorConfig = m_model.createResource( "http://purl.org/semwiq/mediator/config#FederatorConfig" );
    
    /** <p>Configuration of the graphical user interface (used for both, the web application 
     *  and the Java swing client</p>
     */
    public static final Resource GUIConfig = m_model.createResource( "http://purl.org/semwiq/mediator/config#GUIConfig" );
    
    public static final Resource InstanceBasedFederatorConfig = m_model.createResource( "http://purl.org/semwiq/mediator/config#InstanceBasedFederatorConfig" );
    
    /** <p>Main configuration of the SemWIQ Mediator</p> */
    public static final Resource MediatorConfig = m_model.createResource( "http://purl.org/semwiq/mediator/config#MediatorConfig" );
    
    /** <p>Represents a prefix mapping</p> */
    public static final Resource PrefixMapping = m_model.createResource( "http://purl.org/semwiq/mediator/config#PrefixMapping" );
    
    /** <p>A sample query to show in the GUI after startup.</p> */
    public static final Resource SampleQuery = m_model.createResource( "http://purl.org/semwiq/mediator/config#SampleQuery" );
    
    /** <p>Jena Assemler specification for a virtual mediator dataset</p> */
    public static final Resource SemWIQDataset = m_model.createResource( "http://purl.org/semwiq/mediator/config#SemWIQDataset" );
    
    public static final Resource TripleBasedFederatorConfig = m_model.createResource( "http://purl.org/semwiq/mediator/config#TripleBasedFederatorConfig" );
    
    /** <p>Configuration of the UserRegistry</p> */
    public static final Resource UserRegistryConfig = m_model.createResource( "http://purl.org/semwiq/mediator/config#UserRegistryConfig" );
    
    public static final Resource VirtualDataset = m_model.createResource( "http://purl.org/semwiq/mediator/config#VirtualDataset" );
    

    /* Vocabulary individuals */

}

/*
@footer@
*/

