/*****************************************************************************
 * Source code information
 * -----------------------
 * Original author    Andreas Langegger, Johannes Kepler University Linz, Austria
 * Author email       al@jku.at
 * Package            @package@
 * Web site           @website@
 * Created            29 Jul 2009 19:46
 * @copyright@
 *****************************************************************************/

// Package
///////////////////////////////////////
package at.jku.semwiq.mediator.vocabulary;

// Imports
///////////////////////////////////////
import com.hp.hpl.jena.rdf.model.*;


/**
 * Vocabulary definitions from file:vocabulary/www.w3.org/2004/02/skos/core
 * @author Auto-generated by schemagen on 29 Jul 2009 19:46
 */
public class SKOSCore {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2004/02/skos/core#CollectableProperty#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    



    /* Vocabulary properties */


    /* Vocabulary classes */


    /* Vocabulary individuals */

}

/*
@footer@
*/

