/*****************************************************************************
 * Source code information
 * -----------------------
 * Original author    Andreas Langegger, Johannes Kepler University Linz, Austria
 * Author email       al@jku.at
 * Package            @package@
 * Web site           @website@
 * Created            13 Jan 2010 14:17
 * @copyright@
 *****************************************************************************/

// Package
///////////////////////////////////////
package at.jku.semwiq.mediator.vocabulary;

// Imports
///////////////////////////////////////
import com.hp.hpl.jena.rdf.model.*;


/**
 * Vocabulary definitions from file:vocabulary/purl.org/semwiq/mediator/suv.n3
 * @author Auto-generated by schemagen on 13 Jan 2010 14:17
 */
public class SUV {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/semwiq/mediator/sdv#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    



    /* Vocabulary properties */

    /** <p>disables a user account</p> */
    public static final Property disabled = m_model.createProperty( "http://purl.org/semwiq/mediator/sdv#disabled" );
    
    /** <p>user account password</p> */
    public static final Property password = m_model.createProperty( "http://purl.org/semwiq/mediator/sdv#password" );
    

    /* Vocabulary classes */

    /** <p>SemWIQ user</p> */
    public static final Resource User = m_model.createResource( "http://purl.org/semwiq/mediator/sdv#User" );
    

    /* Vocabulary individuals */

}

/*
@footer@
*/

